language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  

after_success:
  - docker build -t simons22d/jade ./udagram-api-feed
  # - docker build -t simons22d/udagram-api-user:v4 ./udagram-api-user
  # - docker build -t simons22d/udagram-frontend:v4 ./udagram-frontend
  # - docker build -t simons22d/reverseproxy:v4 ./udagram-reverseproxy
  #push image to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push simons22d/jade
  # - docker push simons22d/udagram-api-user:v4
  # - docker push simons22d/udagram-frontend:v4
  # - docker push simons22d/reverseproxy:v4
