language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -f udagram-api-feed/Dockerfile .
  - docker tag udagram-api-feed simons22d/udagram-api-feed:v2
  - docker build -f udagram-api-user/Dockerfile .
  - docker tag udagram-api-user simons22d/udagram-api-user:latest
  - docker build -f udagram-frontend/Dockerfile .
  - docker tag udagram-frontend simons22d/udagram-frontend:v2
  - docker build -f reverse-proxy/Dockerfile .
  - docker tag reverse-proxy simons22d/reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push simons22d/udagram-api-feed
  - docker push simons22d/udagram-api-user
  - docker push simons22d/udagram-frontend
  - docker push simons22d/reverseproxy
